language: node_js
dist: trusty
sudo: required
node_js: 10
env:
  - PATH=$HOME/purescript:$PATH
install:
  - wget -O $HOME/purescript.tar.gz https://github.com/purescript/purescript/releases/download/v0.13.8/linux64.tar.gz
  - tar -xvf $HOME/purescript.tar.gz -C $HOME/
  - chmod a+x $HOME/purescript
  - npm install -g spago bower
script:
  - spago build
  - bower install && npm install && npm run compile:bower
